# MLOps Pipeline Configuration with Environment Variable Support

project:
  name: "mlops-pipeline"
  version: "1.0.0"
  description: "End-to-end MLOps pipeline with multi-model support"

# Environment-aware settings
environment: ${ENVIRONMENT:-development}
debug: ${DEBUG:-true}

# MLflow Configuration
mlflow:
  tracking_uri: ${MLFLOW_TRACKING_URI:-file:./mlruns}
  experiment_name: ${MLFLOW_EXPERIMENT_NAME:-mlops-pipeline}

# Weights & Biases
wandb:
  api_key: ${WANDB_API_KEY:-}
  project: ${WANDB_PROJECT:-mlops-pipeline}
  entity: ${WANDB_ENTITY:-}

# API Configuration
api:
  host: ${API_HOST:-0.0.0.0}
  port: ${API_PORT:-8000}
  workers: ${API_WORKERS:-1}

# Models configuration (unchanged)
models:
  available:
    bert_classifier:
      source: "huggingface"
      model_name: "bert-base-uncased"
      task: "classification"
      fine_tunable: true
    
    distilbert_classifier:
      source: "huggingface" 
      model_name: "distilbert-base-uncased"
      task: "classification"
      fine_tunable: true
    
    custom_lstm:
      source: "local"
      model_path: "models/custom_lstm.pt"
      task: "classification"
      architecture: "lstm"

  default: "bert_classifier"
  comparison_set: ["bert_classifier", "distilbert_classifier"]

# Data configuration
data:
  raw_path: "data/raw"
  processed_path: "data/processed"
  test_size: 0.2
  random_state: 42

# Training configuration
training:
  batch_size: 32
  learning_rate: 2e-5
  epochs: 10
  max_seq_length: 512
  warmup_steps: 500

# Monitoring configuration
monitoring:
  enabled: ${DRIFT_DETECTION_ENABLED:-true}
  drift_threshold: 0.05
  check_interval: ${DRIFT_CHECK_INTERVAL:-3600}
  prometheus_port: ${PROMETHEUS_PORT:-8001}

# Logging configuration
logging:
  level: ${LOG_LEVEL:-INFO}
  file: ${LOG_FILE:-logs/mlops.log}
